type User @table {
  firstName: String!
  lastName: String!
  email: String!
  role: String!
  createdAt: Timestamp!
  phoneNumber: String
  department: String
}

type Account @table {
  name: String!
  industry: String!
  createdAt: Timestamp!
  website: String
  phoneNumber: String
  address: String
}

type Opportunity @table {
  name: String!
  status: String!
  value: Float!
  expectedCloseDate: Date!
  createdAt: Timestamp!
  description: String
  account: Account!
  salesRepresentative: User!
}

type Project @table {
  name: String!
  startDate: Date!
  status: String!
  createdAt: Timestamp!
  endDate: Date
  description: String
  account: Account!
  projectManager: User!
}

type ProjectAssignment @table(key: ["project", "user"]) {
  role: String!
  assignedAt: Timestamp!
  endDate: Date
  hoursAllocated: Int
  project: Project!
  user: User!
}